### ISSUE TITLE
Cliente se cierra solo al estar minimizado y recibir un golpe de un NPC

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#85]
El bug consiste en dejar minimizado el cliente y al momento de recibir un ataque de un NPC arroja el error que adjunto en el screenshot.
![2ikntpj](https://user-images.githubusercontent.com/7727108/47727552-5ca07180-dc3b-11e8-9bd5-c903653a9617.jpg)

**Comment by RecoX** [comment]
I can reproduce the same error but in a different way.

When I start the application in Visual Basic and then I connect to a server it throws this error:

[imagen](https://media.discordapp.net/attachments/496021980923953155/506725502577541120/Screen_Shot_2018-10-30_at_8.05.15_PM.png)

And is pointing to this function:
```
Public Sub Engine_EndScene(ByRef destRect As RECT, Optional ByVal hWndDest As Long = 0)
'***************************************************
'Author: Ezequiel Juárez (Standelf)
'Last Modification: 29/12/10
'Blisse-AO | DD EndScene & Present
'***************************************************
    
    
    If hWndDest = 0 Then
        DirectDevice.EndScene
        DirectDevice.Present destRect, ByVal 0&, ByVal 0&, ByVal 0&
    Else
        DirectDevice.EndScene
        DirectDevice.Present destRect, ByVal 0, hWndDest, ByVal 0
    End If
End Sub
```
But is random, because I tried again and it works fine.

**Comment by juandpr** [comment]
Esto me pasa a veces cuando trato de logear
